apiVersion: v1
appVersion: "0.1.0"
description: Network File System Services for your Cloud-Native Environment
icon: https://rook.io/images/logos/rook/rook-logo-color-on-transparent.png
name: rook-nfs
sources:
- https://github.com/rook/rook
version: 0.0.1
