# Service acccount for the operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-nfs-operator
  #namespace: rook-nfs-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-nfs-provisioner
  #namespace: rook-nfs-system
